services:
  hotlinkstuff:
    image: ghcr.io/jbkunama1/hai-hotlinkstuff:latest
    container_name: hai-hotlinkstuff
    restart: unless-stopped
    ports:
      - "8095:80"
    environment:
      APP_PASSWORD: ${APP_PASSWORD:-hotstuff}
    volumes:
      - ${DATA_PATH:-/data}:/var/www/data
    networks:
      - highfishNetwork

networks:
  highfishNetwork:
    external: true
    name: highfishNetwork
